module.exports = {
	CMD: {
		FILE_REQUEST  : 'CMD_MAIN_TYPE/FILE_REQUEST',
		NORMAL_REQUEST: 'CMD_MAIN_TYPE/NORMAL_REQUEST'
	},
	CMD_TYPE: {
		FILE_DOWNLOAD: 'CMD_SUB_TYPE/FILE_DOWNLOAD',
		FILE_UPLOAD  : 'CMD_SUB_TYPE/FILE_UPLOAD'
	},
	RESULT: {
		OK    : 'RESULT_TYPE/OK',
		FAILED: 'RESULT_TYPE/FAILED'
	}
};